### ISSUE TITLE
StackOverflow with ImmutableLists

### ISSUE THREAD

**Issue by g8OW0oF6** [mapstruct/mapstruct#1825]
While trying to compile this code, I get a stackoverflow:
```java
@Mapper
public abstract class StackOverflowMapper {

        public abstract A mapBtoA(B other);

	public abstract AElement mapBElementToAElement(BElement other);

	protected ImmutableList<AElement> mapImmutableList(ImmutableList<BElement> test) {
                var mapped = test.stream().map(this::mapBElementToAElement).collect(Collectors.toList());
		return ImmutableList.copyOf(mapped);
	}

}

class AElement {
	public String stuff;
}

class A {
	public ImmutableList<AElement> test;
}

class BElement {
	public String stuff;
}

class B {
	public ImmutableList<BElement> test;
}
```
Error: 
```
Internal error in the mapping processor: java.lang.StackOverflowError    at 
jdk.compiler/com.sun.tools.javac.code.Types.freshTypeVariables(Types.java:4417)      at 
jdk.compiler/com.sun.tools.javac.code.Types.capture(Types.java:4363)    at 
jdk.compiler/com.sun.tools.javac.code.Types.isSubtype(Types.java:1096)       at 
jdk.compiler/com.sun.tools.javac.code.Types.isSubtypeUncheckedInternal(Types.java:1022)      at 
jdk.compiler/com.sun.tools.javac.code.Types.isSubtypeUnchecked(Types.java:1008)      at 
jdk.compiler/com.sun.tools.javac.code.Types.isConvertible(Types.java:607)       at 
jdk.compiler/com.sun.tools.javac.code.Types.isAssignable(Types.java:2319)    at 
jdk.compiler/com.sun.tools.javac.code.Types.isAssignable(Types.java:2287)    at 
jdk.compiler/com.sun.tools.javac.model.JavacTypes.isAssignable(JavacTypes.java:105)          at 
org.mapstruct.ap.spi.DefaultBuilderProvider.isBuildMethod(DefaultBuilderProvider.java:269)     at 
org.mapstruct.ap.spi.DefaultBuilderProvider.findBuildMethods(DefaultBuilderProvider.java:236)        at 
org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:167)         at 
org.mapstruct.ap.spi.ImmutablesBuilderProvider.findBuilderInfo(ImmutablesBuilderProvider.java:49)       at 
org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:96)          at 
org.mapstruct.ap.internal.model.common.TypeFactory.findBuilder(TypeFactory.java:530)         at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:189)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)    at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:280)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)    at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:280)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)    at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:280)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)    at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:280)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)    at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:280)     at 
org.mapstruct.ap.internal.model.common.TypeFactory.getType(TypeFactory.java:180)        at 
org.mapstruct.ap.internal.model.common.BuilderType.create(BuilderType.java:98)       at 
org.mapstruct.ap.internal.model.common.Type.<init>(Type.java:160)
...
```
Java version: 11.0.2, vendor: AdoptOpenJDK

I know ImmutableLists are not supported, but shouldn't this work with the `mapImmutableList` method?

**Comment by filiphr** [comment]
Where does this `ImmutableList` come from? I think that this might be similar to #1751, which is fixed with PR #1807. Is it possible for you to run your code on the PR?

**Comment by g8OW0oF6** [comment]
The `ImmutableList` is from Google Guava. I tried running my code with the PR, but the problem still persists.

By experimenting, I found out that this code is enough to provoke the stack overflow:
```java
@Mapper
public abstract class StackOverflowMapper {

	protected ImmutableList<AElement> mapImmutableList(ImmutableList<BElement> test) {
		return null;
	}

}
```

**Comment by chris922** [comment]
Thanks @g8OW0oF6 for reporting the issue and providing a short reproducer! Imho that's definitely a bug as exceptions shouldn't occur.

**Comment by chris922** [comment]
@filiphr I was able to create a reproducer test and test this with your PR #1751 - you are right, this here is the same issue. I will file a PR with the reproducer, but we can probably close this issue here.

@g8OW0oF6 you checked out the branch `1751` from @filiphr s fork or the mapstruct master (which is not yet updated)? The reproducer I just created and that works with PR #1751 looks like the last example you provided.

**Comment by filiphr** [comment]
@chris922 how different is your reproducer to the one in the #1807 PR? The problem is the cyclic dependency with the same type. 

I also think that this would be solved with PR #1811 by @sjaakd and his amazing refactoring.

@g8OW0oF6 closing this ticket in favour of #1751.
