### ISSUE TITLE
NPE when running MapStruct from IntelliJ 2020.3EAP

### ISSUE THREAD

**Issue by bjansen** [mapstruct/mapstruct#2215]
- [x] Is this an issue (and hence not a question)? 

I recently upgraded to IntelliJ 2020.3 EAP and the MapStruct annotation processor throws a NPE when compiling a `@Mapper` class. 

```
C:\Users\bj\IdeaProjects\untitled2\src\main\java\PersistenceMapper.java:5:17
java: Internal error in the mapping processor: java.lang.NullPointerException  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.createManifestUrl(DefaultVersionInformation.java:182)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.openManifest(DefaultVersionInformation.java:153)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getLibraryName(DefaultVersionInformation.java:129)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getCompiler(DefaultVersionInformation.java:122)  
	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.fromProcessingEnvironment(DefaultVersionInformation.java:95)  
	at org.mapstruct.ap.internal.processor.DefaultModelElementProcessorContext.<init>(DefaultModelElementProcessorContext.java:54)  
	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:264)  
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  
	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:59)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)  
	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:162)  
	at com.sun.proxy.$Proxy18.process(Unknown Source)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)  
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)  
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)  
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)  
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)  
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:219)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:496)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:348)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:272)  
	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:226)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1436)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1100)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1219)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:832)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:419)  
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)  
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)  
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)  
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)  
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)  
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  
	at java.base/java.lang.Thread.run(Thread.java:834)  
```

When I debug the compilation process, I can see that it's caused by the `ProcessingEnvironment` instance which is now a `Proxy` in `org.mapstruct.ap.internal.processor.DefaultVersionInformation#getCompiler(javax.annotation.processing.ProcessingEnvironment)`.

In 2020.2, `processingEnv.getClass().getName()` returns `com.sun.tools.javac.processing.JavacProcessingEnvironment`.
In 2020.3, `processingEnv.getClass().getName()` returns `com.sun.proxy.$Proxy19`, and later on `clazz.getClassLoader().getResource(classFileName)` returns `null`.

**Steps to reproduce**
* open the attached project in IDEA 2020.3 EAP
* compile `PersistenceMapper.java`

**Steps to debug**
* The project should be pre-configured to launch the compilation process with a debugger listening on port 5050
* Run the debug configuration to attach the IDE to the compilation process
* Put a breakpoint in `org.mapstruct.ap.internal.processor.DefaultVersionInformation#getCompiler(javax.annotation.processing.ProcessingEnvironment)`
* Recompile `PersistenceMapper.java` using F9

**Additional info**
> IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4203.26, built on September 30, 2020
IntelliJ IDEA EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1098.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: PlantUML integration, Lombook Plugin, YourKit Java Profiler 2019.8-b137 Integration, org.sonarlint.idea, MavenRunHelper, com.dmarcotte.handlebars

MapStruct version 1.4.0.Final

**Comment by bjansen** [comment]
More info:

![image](https://user-images.githubusercontent.com/281528/94928154-8a476280-04c3-11eb-981c-c551aa0a0375.png)

https://github.com/JetBrains/intellij-community/blob/master/jps/jps-builders-6/src/org/jetbrains/jps/javac/APIWrappers.java

**Comment by filiphr** [comment]
Thanks a lot for this issue @bjansen. I was not aware about [IDEA-250718](https://youtrack.jetbrains.com/issue/IDEA-250718). What they did there is amazing for us, means that the last missing pain points with IDEA are resolved. 

In the meantime I am trying to fix the NPE that it is happening and will try to release 1.4.1 with those changes

**Comment by bjansen** [comment]
The only downside is that people who are stuck with an older version of MapStruct will have to use a workaround to build their project (`-Djps.track.ap.dependencies=false`)

**Comment by filiphr** [comment]
Or they'll have to upgrade to a newer version 😉. 

Upgrading MapStruct shouldn't be a big deal. It generates code during compilation, so you can easily compare the generated code before and after. 

We will also try to fix any possible regressions asap and release 1.4.1

**Comment by victordfb** [comment]
I'm using mapstruct-jdk8 but this bug fix isn't avaible in that artifact. Unfortunatelly I will regress to previous version of IntelliJ to keep build my project.
:(

**Comment by filiphr** [comment]
@victordfb there is no reason for you to regress to a preview version of IntelliJ. Did you read https://github.com/mapstruct/mapstruct/issues/2215#issuecomment-703120512?

I would also advise using 1.4.1.Final and use `mapstruct` instead of `mapstruct-jdk8`. `mapstruct-jdk8` is deprecated and identical to `mapstruct` since 1.3

**Comment by victordfb** [comment]
Yes. I don't know if I am doing something wrong. But putting this parameter in both VM options neither in program arguments solved the problem. Neither updating to **org.mapstruct:mapstruct:1.4.1.Final** the problem has gone.

**Comment by filiphr** [comment]
And you are sure that the `mapstruct-processor` is also 1.4.1.Final? As you need to have the processor to 1.4.1. I am using it for a while already (I use IntelliJ EAP) and it works without problems.

**Comment by lixinchuang** [comment]
I encoutered the same question,  I update mapstruct to the lastest version ,1.4.1;  but it does't work

**Comment by afwlehmann** [comment]
> @victordfb there is no reason for you to regress to a preview version of IntelliJ. Did you read [#2215 (comment)](https://github.com/mapstruct/mapstruct/issues/2215#issuecomment-703120512)?
> 
> I would also advise using 1.4.1.Final and use `mapstruct` instead of `mapstruct-jdk8`. `mapstruct-jdk8` is deprecated and identical to `mapstruct` since 1.3

Getting rid of `mapstruct-jdk8` and upgrading both `mapstruct` as well as `mapstruct-processor` to `1.4.1.Final` solved the issue for me. Thanks a lot!

**Comment by MFAshby** [comment]
Same, upgrade to 1.4.1.FINAL fixed it too, just remember to select 'Reload All Maven Projects' in intellij after changing the pom.xml files! (if you are using maven)

**Comment by victordfb** [comment]
I was missing update mapstruct-processor version. After that everything worked fine!
Thank you!

**Comment by ishitaagnihotri12** [comment]
This thing took literally 3 hours of my work time. Finally i was able to find this issue here.
Back to previous version.
[https://stackoverflow.com/questions/43723314/internal-error-in-the-mapping-processor-java-lang-nullpointerexception]
This above link answer is of no use. If somebody can comment there this version problem i think it will help a lot more audience.
Thank you !

**Comment by filiphr** [comment]
@ishitaagnihotri12 the StackOverflow question you are referencing has nothing to do with this problem. Have a look at https://stackoverflow.com/questions/65112406/intellij-idea-mapstruct-java-internal-error-in-the-mapping-processor-java-lang for the solution and also have a look at the other comments in this issue.

There is no need to rollback IntelliJ. Upgrade MapStruct to 1.4.1.Final and the problem is gone.

**Comment by ishitaagnihotri12** [comment]
@filiphr  Actually first i updated it to 1.4.1 , it didn't helped me so I went back to previous version. 
And while doing build I was getting this **internal-error-in-the-mapping-processor-java-lang-nullpointerexception**  and this was the only link on stack that i came across and it didn't helped.

**Comment by filiphr** [comment]
Make sure that you do what is explained in https://github.com/mapstruct/mapstruct/issues/2215#issuecomment-737904080 when upgrading to 1.4.1.Final

**Comment by victordfb** [comment]
@ishitaagnihotri12 In my case I forgot to update the mapstruct-processor version. Remeber that its declaration is inside maven compiler plugin so it is easily forgetable to update.

**Comment by oday-xiexin** [comment]
> @ishitaagnihotri12 the StackOverflow question you are referencing has nothing to do with this problem. Have a look at https://stackoverflow.com/questions/65112406/intellij-idea-mapstruct-java-internal-error-in-the-mapping-processor-java-lang for the solution and also have a look at the other comments in this issue.
> 
> There is no need to rollback IntelliJ. Upgrade MapStruct to 1.4.1.Final and the problem is gone.

I also encountered this problem after upgrading idea2020.3, but can I smoothly upgrade from 1.2.0.final to 1.4.1.final? Will there be other compatibility issues? Are there unexpected bugs

**Comment by oday-xiexin** [comment]
> 否则他们将不得不升级到新版本 😉。
> 
> 升级MapStruct没什么大不了的。它在编译期间生成代码，因此您可以轻松地比较之前和之后生成的代码。
> 
> 我们还将尝试尽快修复所有可能的回归并发布1.4.1。

When I upgrade from 1.2 to 1.41, the compiler prompts import org.mapstruct.Mapper  can't find

**Comment by khorchanov** [comment]
Upgrading to 1.4.1.Final solved the issue for me, do not forget to have this version on your processor too
Thanks

**Comment by hospino11** [comment]
> The only downside is that people who are stuck with an older version of MapStruct will have to use a workaround to build their project (`-Djps.track.ap.dependencies=false`)

This workaround worked for me. Thanks @bjansen

**Comment by luanbk** [comment]
Hi @filiphr, i get an exact problem and upgrading from 1.3.1.Final solves the problem, but other problem comes, which is:
"java: No implementation was created for ABCMapper due to having a problem in the erroneous element java.util.ArrayList. Hint: this often means that some other annotation processor was supposed to process the erroneous element. You can also enable MapStruct verbose mode by setting -Amapstruct.verbose=true as a compilation argument."

**Comment by filiphr** [comment]
@luanbk can you please do what is described in the error and share the output with us?

**Comment by ifelse-codes** [comment]
> 1.4.1.Final

yup using `1.4.1.Final` solved the issue for me as well

**Comment by musjassani** [comment]
Hi, do not forget to sync maven project after upgrade to 1.4.1.Final

**Comment by x7Git** [comment]
The update didn't work for me, maven now builds but single JUnit tests can still not be executed
``java: Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.createManifestUrl(DefaultVersionInformation.java:182)  	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.openManifest(DefaultVersionInformation.java:153)  	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getLibraryName(DefaultVersionInformation.java:129)  	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.getCompiler(DefaultVersionInformation.java:122)  	at org.mapstruct.ap.internal.processor.DefaultVersionInformation.fromProcessingEnvironment(DefaultVersionInformation.java:95)  	at org.mapstruct.ap.internal.processor.DefaultModelElementProcessorContext.<init>(DefaultModelElementProcessorContext.java:50)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:218)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:156)  	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:109)  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)  	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:213)  	at org.mapstruct.ap.MappingProcessor.process(Unknown Source)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)  	at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$89/0000000000000000.call(Unknown Source)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:231)  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:498)  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:350)  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:274)  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:228)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1441)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1100)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1224)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:832)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:419)  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$71/0000000000000000.run(Unknown Source)  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  	at java.base/java.lang.Thread.run(Thread.java:836)
``
my IntelliJ version 
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155,

**Comment by filiphr** [comment]
@x7Git if you are seeing that error it means that the `mapstruct-processor` is still on 1.3. Please make sure that both `mapstruct` and the `mapstruct-processor` are updated to 1.4.1.Final

**Comment by carlopolisini** [comment]
I am running a pretty old project with Jhpster and Spring Boot 1.5, it is a side project but still needed. solutions proposed above does not work since other libraries go in error updating mapstruct stack to 1.4.1. Best way it is ro regress IntelliJ 2020.2, that's ok for now.

**Comment by filiphr** [comment]
@carlopolisini it would be good to know which other libraries have errors when updating MapStruct to 1.4.1. MapStruct is only used during compilation, so it shouldn't really affect your other libraries.

Btw you don't have to regress IntelliJ to 2020.2. You can also use 2020.3 and add `-Djps.track.ap.dependencies=false` to File | Settings | Build, Execution, Deployment | Compiler | Build process VM options field.

**Comment by manoranjanb** [comment]
Even after upgrading mapstruct and mapstruct-processor to 1.4.1.Final, mapstruct isnt able to generate implementation at compilation...I get errors saying 
`No property named "<xyz>" exists in source parameter(s). Did you mean "null"?`

**Comment by filiphr** [comment]
@manoranjanb as I mentioned in the other issue you opened. When you are using Lombok 1.18.16 then please check the [Lombok Changelog](https://projectlombok.org/changelog).

**Comment by jdzhang1221** [comment]
> > 否则他们将不得不升级到新版本 😉。
> > 升级MapStruct没什么大不了的。它在编译期间生成代码，因此您可以轻松地比较之前和之后生成的代码。
> > 我们还将尝试尽快修复所有可能的回归并发布1.4.1。
> 
> When I upgrade from 1.2 to 1.41, the compiler prompts import org.mapstruct.Mapper can't find

So how was it solved in the end？

**Comment by ravenblackdusk** [comment]
on intellij 2020.3.2 upgrading `mapstruct` and `mapstruct-processor` to `1.4.1.Final` or `1.4.2.Final` and reloading all maven projects didn't work for me. I still get the NPE. `-Djps.track.ap.dependencies=false` however does work.

**Comment by alpizano** [comment]
This worked for me . Thank you.

**Comment by cmasantos** [comment]
> on intellij 2020.3.2 upgrading `mapstruct` and `mapstruct-processor` to `1.4.1.Final` or `1.4.2.Final` and reloading all maven projects didn't work for me. I still get the NPE. `-Djps.track.ap.dependencies=false` however does work.

This^,
I had to reload the project to make it work.

**Comment by tufac2** [comment]
It worked for me to move to 1.4.1.Final and reloading maven dependencies

**Comment by zhaoxilingcheng** [comment]
> @filiphr Actually first i updated it to 1.4.1 , it didn't helped me so I went back to previous version.
> And while doing build I was getting this **internal-error-in-the-mapping-processor-java-lang-nullpointerexception** and this was the only link on stack that i came across and it didn't helped.

亲测有效，谢谢 ^_^

**Comment by voronin-de** [comment]
> reload

This. If you have trouble, because apparently IntelliJ doesn't recognize the new version, close the project and open it anew (I am not sure if there's any other way to reload the project) and the error will be gone.

**Comment by ducquoc** [comment]
Thank you. The work-around works for me ( -Djps.track.ap.dependencies=false ): https://i.stack.imgur.com/QyDMc.png
