### ISSUE TITLE
Immutables support with builders and Context

### ISSUE THREAD

**Issue by thantsoun** [mapstruct/mapstruct#2721]
- [x] Is this an issue (and hence not a question)? 

Hi, I have a project that uses a mix of immutables and standard beans that have cycle references. Hence I am using a Context I got out of stack overflow to avoid infinite recursions when mapping the objects. My project is a lot more complicated that this example. For example I have immutables objects with properties that are normal beans which in turn have quite an elaborate structure forming a graph with cycles. The problem is that with the latest version of mapstruct the generated mapping method does not work well in conjunction with my Context class and the immutables builder. The context class stores the objects that have been mapped using the ```storeMappedInstance``` method and retrieves previously stored objects with the ```getMappedInstance```. Both methods in the Context are annotated with ```@BeforeMapping```. With the latest version I get a compilation error since the return type pof the ```storeMappedInstance``` method which is the builder does not match the type of the object itself. Using the 1.5.0.Beta2 version this method is simply not injected while the ```storeMappedInstance``` is, which does not make sense. Now with the beta version my project compiles and behaves as expected but I wonder if this is a regression. With what criteria one of the methods is injected and the other is not? Would it be possible to make the new version work with immutables while properly trying to retrieve stored objects? Now this is not required for cycle references since we cannot have them with immutables objects but it might be useful in case of collections which hold multiple times a single object. Below you can find the Java code as well as a link the a sample project in github.

### Simple Immutable Java Class
```java
@Value.Immutable
public interface SomeImmutableClass {
    String getName();
}
```
### Corresponding DTO
```java
@Value.Immutable
public interface SomeImmutableClassDto {
    String getName();
}
```
### Mapper
```java
@Mapper
public interface SomeMapper {
    SomeImmutableClassDto toDto(SomeImmutableClass someClass, @Context CycleAvoidingMappingContext context);
    SomeImmutableClass toDto(SomeImmutableClassDto someClass, @Context CycleAvoidingMappingContext context);
}
```
### Context
```java
public class CycleAvoidingMappingContext {

    private final Map<Object, Object> knownInstances = new IdentityHashMap<Object, Object>();
    
    @BeforeMapping
    public <T> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
        return targetType.cast(knownInstances.get(source));
    }

    @BeforeMapping
    public void storeMappedInstance(Object source, @MappingTarget Object target) {
        knownInstances.put( source, target );
    }
}
```
### Generated mapping method with 1..4.2-Final
```java
@Override
public SomeImmutableClassDto toDto(SomeImmutableClass someClass, CycleAvoidingMappingContext context) {
    SomeImmutableClassDto target = context.getMappedInstance( someClass, Builder.class );
    if ( target != null ) {
       return target;
    }

    if ( someClass == null ) {
        return null;
    }

    Builder someImmutableClassDto = ImmutableSomeImmutableClassDto.builder();

    context.storeMappedInstance( someClass, someImmutableClassDto );

    someImmutableClassDto.name( someClass.getName() );

    return someImmutableClassDto.build();
}
```
### Generated mapping method with 1.5.0-Beta2
```java
@Override
public SomeImmutableClassDto toDto(SomeImmutableClass someClass, CycleAvoidingMappingContext context) {
    if ( someClass == null ) {
        return null;
    }

    ImmutableSomeImmutableClassDto.Builder someImmutableClassDto = ImmutableSomeImmutableClassDto.builder();

    context.storeMappedInstance( someClass, someImmutableClassDto );

    someImmutableClassDto.name( someClass.getName() );

    return someImmutableClassDto.build();
}
```
The complete test project based on gradle can be found here: [Test Project](https://github.com/thantsoun/ImmutablesMapstructTest)

Thanks a lot!

**Comment by thantsoun** [comment]
Hello team,

some feedback on this would be greatly appreciated!

Thanks a lot,

Regards

Thanos

**Comment by guillemsuetta** [comment]
I have the same issue, is there any workaround?

**Comment by guillemsuetta** [comment]
> I have the same issue, is there any workaround?

Never mind I solved the issue using a beta version where this problem is solved (1.5.0.Beta2)

**Comment by Zegveld** [comment]
Hmmm I'd say this is definitely a bug.
Only noticed this report today, still present with the `1.5.0.RC1` version.

Apparently for interfaces the retrieving bit is broken. Going to analyze this issue and hopefully create a PR with a fix for it in time for the `1.5.0` release.

**Comment by Zegveld** [comment]
Just finished with the analysis.

It works as expected. The `1.4.2.Final` code was incorrect, the code you see for the `1.5.0.Beta2` is correct.

The bit that was generated below is invalid:
```
SomeImmutableClassDto target = context.getMappedInstance( someClass, Builder.class );
```
The return type of the `getMappedInstance` method is `SomeImmutableClassDto.Builder` not `SomeImmutableClassDto`.

As already specified in the opening post: immutable objects cannot have cyclic references, because then you can never create them. This is inherent to the way immutable objects are constructed.

> but it might be useful in case of collections which hold multiple times a single object.
If there is a situation in which this becomes useful, then please create a new issue with the feature request for that situation.

I hope this suffices as explanation why the before method is not used anymore.

**Comment by Michael-Frank** [comment]
I've ran into a similar issue with mapstruct in conjunction with protobuf and https://github.com/entur/mapstruct-spi-protobuf

The solution (for mapstruct >1.4.2-Final) is to simply give the return type its own generic, decoupling it from the TargetType:
(Thx @Zegveld for pointing me in the right direction with your analysis)

```java
public static class CycleAvoidingMappingContext {
        private Map<Object, Object> knownInstances = new IdentityHashMap<>();

        @BeforeMapping
        public <C, R> R getMappedInstance(Object source, @TargetType Class<C> constructingType) { /*...*/}
}
```

This produces, as expected:
```java
public class GraphReferenceMapperImpl implements GraphReferenceMapper {

    @Override
    public grpc.GraphNode toGrpc(GraphNode source, GraphReferenceMapperTest.ToGrpcGraphRefMappingContext ctx) {
        grpc.GraphNode target = ctx.getMappedInstance( source, grpc.GraphNode.Builder.class );
        if ( target != null ) {
            return target;
        }
        if ( source == null ) {
            return null;
        }

        grpc.GraphNode.Builder graphNode = grpc.GraphNode.newBuilder();

        ctx.storeMappedInstance( source, graphNode );
        //[..]
    }
}
```

**Comment by thunderhook** [comment]
So, I played with this issue a bit.
Currently with mapstruct `1.5.5.Final` the `CycleAvoidingMappingContext` from the original post ...

```java
public class CycleAvoidingMappingContext {

    private final Map<Object, Object> knownInstances = new IdentityHashMap<Object, Object>();
    
    @BeforeMapping
    public <T> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
        return targetType.cast(knownInstances.get(source));
    }

    @BeforeMapping
    public void storeMappedInstance(Object source, @MappingTarget Object target) {
        knownInstances.put( source, target );
    }
}
```

...without the generic workaround from https://github.com/mapstruct/mapstruct/issues/2721#issuecomment-1299990934 generates valid code.

But, nevertheless it uses the `Builder` as target type instead of the resulting (built) class.
Since this is issue is about a regression that is (at least) providing a compiling code, I will close this issue in favor of #3060
